### ISSUE TITLE
Enhancement request: allow filter by tags. 

### ISSUE THREAD

**Issue by jamesjenner** [animify/colorbook#4]
Not sure how you generate your data, but if possible then it would be nice if the top ten could be filtered by tags. For example, someone could select business card, or UI, or illustration. 

When I say filter, I mean that it shows the top 10 for that tag, not that it filters the current top 10. so you would always see a top 10, just specific to a tag instead of all dribbble entries.

**Comment by animify** [comment]
Timeline data is generated every time a date is loaded, and popular shots are generated & replaced on the hour. This happens [here](/animify/colorbook/blob/master/server/Dribbble.js).

About filtering, yeah seems like a good idea. I would need to also save tags alongside shots so that they're searchable and when selected, the filtered shots will be sorted by likes/views etc.

Will brainstorm a little more about how i'll tackle this, but a great idea nonetheless!
